{% set name = "pytest-freezegun" %}
{% set version = "0.4.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip"
  sha256: 060cdf192848e50a4a681a5e73f8b544c4ee5ebc1fab3cb7223a0097bac2f83f

build:
  noarch: "python"
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - freezegun >0.3
    - pytest >=3.0.0
    - python

test:
  imports:
    - pytest_freezegun

about:
  home: "https://github.com/ktosiek/pytest-freezegun"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE"
  summary: "Wrap tests with fixtures in freeze_time"
  dev_url: "https://github.com/ktosiek/pytest-freezegun"
  description: "Wrap tests with fixtures in freeze_time"

extra:
  recipe-maintainers:
    - duncanmmacleod
